# @package _global_

defaults:
  - base
  - _self_

rl_games:
  model_alias: openvla

model: openvla

paths:
  base_model_dir: playground/Pretrained_models/Qwen3-VL-4B-Instruct-Action

base_model:
  repo_id: StarVLA/Qwen3-VL-4B-Instruct-Action

initialization:
  checkpoint_local_dir: playground/Pretrained_models/Qwen3VL-OFT-Bridge-RT-1
  checkpoint_hf_repo_id: StarVLA/Qwen3VL-OFT-Bridge-RT-1
  checkpoint_filename: checkpoints/steps_5000_pytorch_model.pt

framework:
  name: QwenOFT
  qwenvl:
    enable_gradient_checkpointing: true
  action_model:
    action_dim: 2
    action_env_dim: 2
    loss_type: discrete_ce

trainer:
  learning_rate:
    base: 2.0e-05
    action_model: 1.0e-04
