# @package _global_

rl_games:
  task: deadly_corridor
  env_eval:
    image_size: 84
    frameskip: 4
    deadly:
      action_layout: multibinary_7

datasets:
  vla_data:
    data_mix: deadly_corridor_train
