# @package _global_

rl_games:
  task: flappy
  env_eval:
    image_size: 84
    frameskip: 1

framework:
  action_model:
    action_layout: flappy_categorical_2

datasets:
  vla_data:
    data_mix: flappy_train
