#!/usr/bin/env bash

# export WANDB_MODE=offline
export HF_DATASETS_OFFLINE="${HF_DATASETS_OFFLINE:-1}"
export TRANSFORMERS_OFFLINE="${TRANSFORMERS_OFFLINE:-1}"
export HF_HUB_OFFLINE="${HF_HUB_OFFLINE:-1}"

CONTEXT_WINDOW="${CONTEXT_WINDOW:-5}"
EPISODES_PER_LATENCY="${EPISODES_PER_LATENCY:-200}"
LATENCY_FILTER="${LATENCY_FILTER:-[0,1,2,3,4]}"
PHASE_STEPS="${PHASE_STEPS:-null}"
DATASET_LOCAL_DIR="${DATASET_LOCAL_DIR:-data/flappy_mixed_latency_${EPISODES_PER_LATENCY}ep_per_lat_context${CONTEXT_WINDOW}}"
PROMPT_MAP_PATH="${PROMPT_MAP_PATH:-${DATASET_LOCAL_DIR}/flappy_mixed_latency_train__bridge/latency_prompt_map.json}"

MAX_TRAIN_STEPS="${MAX_TRAIN_STEPS:-5000}"
EVAL_INTERVAL="${EVAL_INTERVAL:-500}"
MID_TRAIN_INTERVAL="${MID_TRAIN_INTERVAL:-${EVAL_INTERVAL}}"
MID_TRAIN_ENABLED="${MID_TRAIN_ENABLED:-true}"
MID_TRAIN_LATENCIES="${MID_TRAIN_LATENCIES:-[0,1,2,3,4]}"
MID_TRAIN_EPISODES="${MID_TRAIN_EPISODES:-5}"
POST_TRAIN_ENABLED="${POST_TRAIN_ENABLED:-true}"
POST_TRAIN_LATENCIES="${POST_TRAIN_LATENCIES:-[0,1,2,3,4]}"
POST_TRAIN_EPISODES="${POST_TRAIN_EPISODES:-20}"
EVAL_AT_PHASE_END="${EVAL_AT_PHASE_END:-false}"
SAVE_AT_PHASE_END="${SAVE_AT_PHASE_END:-false}"

PER_DEVICE_BATCH_SIZE="${PER_DEVICE_BATCH_SIZE:-4}"
GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-32}"
EFFECTIVE_BATCH_SIZE="${EFFECTIVE_BATCH_SIZE:-$((PER_DEVICE_BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS))}"
RUN_ID="${RUN_ID:-wan_oft_flappy_mixed_latency_curriculum_cumulative_context${CONTEXT_WINDOW}_${EPISODES_PER_LATENCY}ep_per_lat_standard_sft_${MAX_TRAIN_STEPS}_effbs${EFFECTIVE_BATCH_SIZE}_224_currentce}"

python examples/rl_games/scripts/launch_train.py \
  model=wan_oft \
  env=flappy \
  init=wan_oft_libero \
  mode=curriculum_cumulative \
  run_id="${RUN_ID}" \
  paths.dataset_local_dir="${DATASET_LOCAL_DIR}" \
  dataset.converted_name=flappy_mixed_latency_train__bridge \
  "dataset.latency_filter=${LATENCY_FILTER}" \
  dataset.episodes_per_latency="${EPISODES_PER_LATENCY}" \
  trainer.distributed_backend=none \
  launch.use_accelerate=false \
  launch.num_processes=1 \
  trainer.gradient_accumulation_steps="${GRADIENT_ACCUMULATION_STEPS}" \
  datasets.vla_data.per_device_batch_size="${PER_DEVICE_BATCH_SIZE}" \
  datasets.vla_data.data_mix=flappy_mixed_latency_train__bridge \
  datasets.vla_data.eval_data_mix=flappy_mixed_latency_train__bridge__val \
  "datasets.vla_data.obs_image_size=[224,224]" \
  datasets.vla_data.image_sequence_length="${CONTEXT_WINDOW}" \
  "datasets.vla_data.observation_indices=[-4,-3,-2,-1,0]" \
  datasets.vla_data.sequential_step_sampling=true \
  datasets.vla_data.eval_sequential_step_sampling=false \
  datasets.vla_data.action_balance.enabled=false \
  datasets.vla_data.latency_curriculum.enabled=true \
  datasets.vla_data.latency_curriculum.strategy=cumulative \
  "datasets.vla_data.latency_curriculum.latencies=${LATENCY_FILTER}" \
  "datasets.vla_data.latency_curriculum.phase_steps=${PHASE_STEPS}" \
  datasets.vla_data.latency_curriculum.eval_at_phase_end="${EVAL_AT_PHASE_END}" \
  datasets.vla_data.latency_curriculum.save_at_phase_end="${SAVE_AT_PHASE_END}" \
  framework.world_model.num_frames="${CONTEXT_WINDOW}" \
  framework.action_model.loss_type=current_discrete_ce \
  trainer.learning_rate.action_query_proj=1.0e-4 \
  trainer.max_train_steps="${MAX_TRAIN_STEPS}" \
  trainer.num_warmup_steps=0 \
  trainer.lr_scheduler_type=cosine_with_min_lr \
  trainer.scheduler_specific_kwargs.min_lr=1.0e-6 \
  trainer.eval_interval="${EVAL_INTERVAL}" \
  trainer.eval_num_batches=50 \
  trainer.eval_action_classification=false \
  trainer.save_interval=0 \
  rl_games.env_eval.enabled=true \
  rl_games.env_eval.eval_backend=eval_core \
  rl_games.env_eval.image_size=224 \
  rl_games.env_eval.vectorized.enabled=false \
  rl_games.env_eval.latency.prompt_map_path="${PROMPT_MAP_PATH}" \
  rl_games.env_eval.mid_train.enabled="${MID_TRAIN_ENABLED}" \
  rl_games.env_eval.mid_train.interval_steps="${MID_TRAIN_INTERVAL}" \
  "rl_games.env_eval.mid_train.latencies=${MID_TRAIN_LATENCIES}" \
  rl_games.env_eval.mid_train.num_episodes="${MID_TRAIN_EPISODES}" \
  rl_games.env_eval.mid_train.max_steps_per_episode=3600 \
  rl_games.env_eval.post_train.enabled="${POST_TRAIN_ENABLED}" \
  "rl_games.env_eval.post_train.latencies=${POST_TRAIN_LATENCIES}" \
  rl_games.env_eval.post_train.num_episodes="${POST_TRAIN_EPISODES}" \
  rl_games.env_eval.post_train.max_steps_per_episode=3600 \
  checkpoint.save_pt_file=true \
  checkpoint.save_training_state=false \
  checkpoint.save_best_model=false \
  checkpoint.save_final_model=true \
  checkpoint.local.keep_last_n=1 \
  checkpoint.load=none \
  "$@"
