#!/usr/bin/env bash

# export WANDB_MODE=offline
export HF_DATASETS_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export HF_HUB_OFFLINE=1

python examples/rl_games/scripts/launch_train.py \
  model=wan_oft \
  env=flappy \
  init=wan_oft_libero \
  run_id=wan_oft_flappy_fix_latency_0_context5_standard_sft_2000_effbs128_224_currentce \
  paths.dataset_local_dir=data/flappy_fix_latency_0_200ep_context5 \
  dataset.converted_name=flappy_train__bridge \
  trainer.distributed_backend=none \
  launch.use_accelerate=false \
  launch.num_processes=1 \
  trainer.gradient_accumulation_steps=32 \
  datasets.vla_data.per_device_batch_size=4 \
  datasets.vla_data.data_mix=flappy_train__bridge \
  datasets.vla_data.eval_data_mix=flappy_train__bridge__val \
  "datasets.vla_data.obs_image_size=[224,224]" \
  datasets.vla_data.image_sequence_length=5 \
  "datasets.vla_data.observation_indices=[-4,-3,-2,-1,0]" \
  datasets.vla_data.sequential_step_sampling=false \
  datasets.vla_data.action_balance.enabled=false \
  framework.world_model.num_frames=5 \
  framework.action_model.loss_type=current_discrete_ce \
  trainer.learning_rate.action_query_proj=1.0e-4 \
  trainer.max_train_steps=2000 \
  trainer.num_warmup_steps=0 \
  trainer.lr_scheduler_type=cosine_with_min_lr \
  trainer.scheduler_specific_kwargs.min_lr=1.0e-6 \
  trainer.eval_interval=500 \
  trainer.eval_num_batches=50 \
  trainer.eval_action_classification=false \
  trainer.save_interval=0 \
  rl_games.env_eval.enabled=true \
  rl_games.env_eval.image_size=224 \
  rl_games.env_eval.vectorized.enabled=false \
  rl_games.env_eval.latency.prompt_map_path=data/flappy_fix_latency_0_200ep_context5/flappy_train__bridge/latency_prompt_map.json \
  rl_games.env_eval.mid_train.enabled=true \
  rl_games.env_eval.mid_train.interval_steps=500 \
  "rl_games.env_eval.mid_train.latencies=[0]" \
  rl_games.env_eval.mid_train.num_episodes=5 \
  rl_games.env_eval.mid_train.max_steps_per_episode=3600 \
  rl_games.env_eval.post_train.enabled=true \
  "rl_games.env_eval.post_train.latencies=[0]" \
  rl_games.env_eval.post_train.num_episodes=20 \
  rl_games.env_eval.post_train.max_steps_per_episode=3600 \
  checkpoint.save_pt_file=true \
  checkpoint.save_training_state=false \
  checkpoint.save_best_model=false \
  checkpoint.save_final_model=true \
  checkpoint.local.keep_last_n=1 \
  checkpoint.load=none
