# @package _global_

rl_games:
  task: flappy
  model_alias: openvla
  initialization_mode: scratch
  action_carrier: native
  env_eval:
    enabled: true
    interval_steps: 100
    num_episodes: 5
    max_episode_steps: 2000
    frameskip: 1
    image_size: 224
    task_description: ""
    deadly:
      action_layout: multibinary_7
    latency:
      mode: single
      values: [0]
      prompt_map_path: null
    mid_train:
      enabled: true
      interval_steps: 100
      latencies: null
      num_episodes: 5
      max_steps_per_episode: 2000
    post_train:
      enabled: true
      latencies: null
      num_episodes: 5
      max_steps_per_episode: 2000
