# @package _global_

defaults:
  - base
  - _self_

rl_games:
  initialization_mode: bridge
  action_carrier: bridge

datasets:
  vla_data:
    include_state: true

dataset:
  single_converted_name: flappy_train__bridge

framework:
  action_model:
    action_dim: 7
    state_dim: 7
    action_horizon: 8
    future_action_window_size: 7
    past_action_window_size: 0

init: cosmo_predict_gr00t_libero
