# @package _global_

defaults:
  - base
  - _self_

rl_games:
  initialization_mode: scratch
  action_carrier: native
  task: cross_task
  env_eval:
    latency:
      mode: mixed
      values: [0, 1, 2, 3, 4, 5]
    mid_train:
      latencies: [0, 1, 2, 3, 4, 5]

mode: cross_task
